spring:
  application:
    name: kafka-demo
  kafka:
    bootstrap-servers: 192.168.215.128:9092
#    producer:
    consumer:
      # By default, when a new consumer group is started, it begins consuming from the latest offset of each partition
      # (i.e., the position right after the last message in that partition). If you want to start consuming from the
      # first message, you need to set the consumer's auto.offset.reset to earliest.
      #
      # If the topic has been consumed by the same consumer group ID before
      # and Kafka has saved the offset of this consumer group,
      # setting "auto.offset.reset=earliest" will not take effect.
      # Only when it does not find the offset will Kafka use the configuration.
      auto-offset-reset: earliest