spring:
  application:
    name: kafka-demo-2
  kafka:
    bootstrap-servers: 192.168.215.128:9092
    consumer:
      max-poll-records: 20
    listener:
      ack-mode: manual
      type: batch

# Custom configuration
kafka:
  topic:
    name: helloTopic
  consumer:
    group: helloGroup